baseurl = "https://gcuisinier.github.io"
title = "$> more /home/gcuisinier/{dev,ops}"
languageCode = "en-us"
disqusShortname = "gcuisinier-github" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "@gcuisinier"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = false

    # Used when a given page doesn't set its own.
    defaultDescription = "Your default page description"
    defaultKeywords = "your,default,page,keywords"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    # theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "github"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Somewhere between Dev and Ops"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "de6689ce4dd5e330b38e55af0f1b5c6b"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/gcuisinier/"
    bitbucket = "https://bitbucket.org/gcuisinier/"
    stackOverflow = ""
    linkedin = "https://www.linkedin.com/in/gcuisinier"
    fiveHundredpx = "https://500px.com/gcuisinier"

    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/gcuisinier"
    youtube = ""
    rss = true

    # Other social-like sidebar links
   # flattr = "gcuisinier"  # populate with your flattr uid